name: Build and Push Docker Image on Release

on:
  release:
    types:
      - created

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23.5'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Run go mod tidy
        run: |
          cd scanner
          go mod tidy

      - name: Build and push Docker image with release tag and latest tag
        run: |
          cd scanner
          docker buildx build --platform linux/amd64,linux/arm64 --tag ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }} --tag ghcr.io/${{ github.repository }}:latest -f ./docker/Dockerfile --push .
