# name: Build and Release

# on:
#   push:
#     tags:
#       - 'v*'

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Set up Go
#       uses: actions/setup-go@v4
#       with:
#         go-version: 1.20

#     - name: Build API
#       run: |
#         cd api
#         go build -o ../build/api

#     - name: Build Scanner
#       run: |
#         cd scanner
#         go build -o ../build/scanner

#     - name: Upload Release Artifacts
#       uses: actions/upload-artifact@v3
#       with:
#         name: build-artifacts
#         path: build/
